const users = ['Mango', 'Poly', 'Ajax', 'Chelsey'];
users.shift();
console.log(users);
users.pop();
console.log(users);
users.unshift('Lux');
console.log(users);
users.push('Jay', 'Kiwi');
console.log(users);
const userToDelete = 'Ajax';
users.splice(users.indexOf(userToDelete), 1);
console.log(users);
const userToInsertBefore = 'Jay';
users.splice(users.indexOf(userToInsertBefore), 0, 'Kong');
console.log(users);
